name: hottie
description: Experiment to run tests inside a running app, for faster feedback loop.
version: 0.0.1-dev.1

homepage: https://github.com/szotp/hottie/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  test_api: ^0.2.19-nullsafety
  flutter_test:
    sdk: flutter

dev_dependencies:
  lint: 

flutter:
  plugin:
    platforms:
      android:
        package: com.szotp.hottie
        pluginClass: HottiePlugin
      ios:
        pluginClass: HottiePlugin
      macos:
        pluginClass: HottiePlugin